In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline

In [3]:
data = pd.read_csv('property_loss1541.csv')
data.head(20)

STATE  latitude  longitude  Number of Inhabited villages  \
0       0  0.108925   0.931385                      0.529412   
1       0  0.108925   0.931385                      0.529412   
2       0  0.108925   0.931385                      0.529412   
3       0  0.108925   0.931385                      0.529412   
4       0  0.108925   0.931385                      0.529412   
5       0  0.108925   0.931385                      0.529412   
6       0  0.108925   0.931385                      0.529412   
7       0  0.108925   0.931385                      0.529412   
8       1  0.230321   0.274940                      0.352941   
9       1  0.230321   0.274940                      0.352941   
10      1  0.230321   0.274940                      0.352941   
11      1  0.230321   0.274940                      0.352941   
12      1  0.230321   0.274940                      0.352941   
13      1  0.230321   0.274940                      0.352941   
14      1  0.230321   0.274940                      0.352941   
15      2  0.716548   0.972193                      0.705882   
16      2  0.716548   0.972193                      0.705882   
17      3  0.702752   1.000000                      0.323529   
18      4  0.664776   0.687824                      0.500000   
19      5  0.519302   0.441298                      0.676471   

    Number of Uninhabited villages  Number of towns  Number of households  \
0                         0.354839          0.68750              0.970588   
1                         0.354839          0.68750              0.970588   
2                         0.354839          0.68750              0.970588   
3                         0.354839          0.68750              0.970588   
4                         0.354839          0.68750              0.970588   
5                         0.354839          0.68750              0.970588   
6                         0.354839          0.68750              0.970588   
7                         0.354839          0.68750              0.970588   
8                         0.161290          0.59375              0.294118   
9                         0.161290          0.59375              0.294118   
10                        0.161290          0.59375              0.294118   
11                        0.161290          0.59375              0.294118   
12                        0.161290          0.59375              0.294118   
13                        0.161290          0.59375              0.294118   
14                        0.161290          0.59375              0.294118   
15                        0.709677          0.46875              0.411765   
16                        0.709677          0.46875              0.411765   
17                        0.064516          0.25000              0.852941   
18                        0.838710          0.21875              0.176471   
19                        0.000000          0.84375              0.352941   

    Total Population  Males Population  Females Population  Area (In sq. km)  \
0           0.647059          0.382353            0.205882          0.024017   
1           0.647059          0.382353            0.205882          0.024017   
2           0.647059          0.382353            0.205882          0.024017   
3           0.647059          0.382353            0.205882          0.024017   
4           0.647059          0.382353            0.205882          0.024017   
5           0.647059          0.382353            0.205882          0.024017   
6           0.647059          0.382353            0.205882          0.024017   
7           0.647059          0.382353            0.205882          0.024017   
8           0.970588          0.676471            0.588235          0.803646   
9           0.970588          0.676471            0.588235          0.803646   
10          0.970588          0.676471            0.588235          0.803646   
11          0.970588          0.676471            0.588235          0.803646   
1

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
scaler = StandardScaler()
scaler.fit(data)

StandardScaler()

In [6]:
scaled_data = scaler.transform(data)

In [7]:
scaled_data

array([[-1.47519628, -0.94628888,  2.01976102, ..., -1.44784553,
        -1.30749831, -0.30351015],
       [-1.47519628, -0.94628888,  2.01976102, ..., -1.18930169,
        -1.18855413,  0.31688517],
       [-1.47519628, -0.94628888,  2.01976102, ..., -0.8273403 ,
         0.71455271,  1.00621331],
       ...,
       [ 1.25247996,  0.46462103, -0.52587417, ...,  1.13759292,
         1.19032942,  1.35087738],
       [ 1.25247996,  0.46462103, -0.52587417, ...,  1.24101046,
        -0.59383325, -1.19963673],
       [ 1.25247996,  0.46462103, -0.52587417, ...,  1.44784553,
        -1.60485876,  1.48874301]])

In [8]:
from sklearn.decomposition import PCA

In [9]:
pca = PCA(n_components=7)

In [10]:
pca.fit(scaled_data)

PCA(n_components=7)

In [11]:
x_pca = pca.transform(scaled_data)

In [12]:
scaled_data.shape

(67, 17)

In [13]:
x_pca.shape

(67, 7)

In [14]:
scaled_data

array([[-1.47519628, -0.94628888,  2.01976102, ..., -1.44784553,
        -1.30749831, -0.30351015],
       [-1.47519628, -0.94628888,  2.01976102, ..., -1.18930169,
        -1.18855413,  0.31688517],
       [-1.47519628, -0.94628888,  2.01976102, ..., -0.8273403 ,
         0.71455271,  1.00621331],
       ...,
       [ 1.25247996,  0.46462103, -0.52587417, ...,  1.13759292,
         1.19032942,  1.35087738],
       [ 1.25247996,  0.46462103, -0.52587417, ...,  1.24101046,
        -0.59383325, -1.19963673],
       [ 1.25247996,  0.46462103, -0.52587417, ...,  1.44784553,
        -1.60485876,  1.48874301]])

In [15]:
x_pca

array([[-1.63089537e+00,  1.86304046e+00,  1.38524484e+00,
        -2.41319603e+00, -7.66500734e-02, -7.36478598e-02,
         1.05923909e+00],
       [-1.61934379e+00,  1.42232639e+00,  1.70870790e+00,
        -2.06628324e+00, -6.97762779e-01,  4.12467215e-01,
         5.06220294e-01],
       [-1.54960901e+00,  1.42058668e+00,  1.08522320e+00,
        -1.93003205e+00, -2.02583888e-01, -1.50045189e-01,
        -3.95353351e-01],
       [-1.47176472e+00,  1.90584870e+00,  1.78855388e+00,
        -1.85629859e+00, -2.08969928e-01,  6.21242609e-01,
         1.50234044e+00],
       [-1.70806249e+00,  1.26190029e+00,  1.62045457e+00,
        -1.98408658e+00, -5.45056709e-01, -2.63646613e-01,
         3.38278374e-01],
       [-1.10995600e+00,  2.46748659e+00,  9.97397672e-01,
        -1.30339410e+00,  5.51522582e-01,  6.91785315e-01,
         3.36729969e-01],
       [-1.59350467e+00,  1.66731770e+00,  2.22734492e+00,
        -1.58398455e+00, -8.33040103e-01,  4.21766087e-01,
         9.9390731

In [16]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error

In [23]:
X = x_pca
y = x_pca['property_loss']

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(x_pca, y, test_size=0.2, random_state=42)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices